// https://nuxt.com/docs/api/configuration/nuxt-config

/**
 * The site's own origin, for the share card and the canonical URL.
 *
 * Deployment metadata, read at build time to make absolute share-card URLs.
 * Cohort and offer content is fetched separately at request time.
 *
 * Unset, the tags fall back to site-relative paths. Most scrapers resolve
 * those against the page they found them on and the card still renders, but
 * the spec asks for absolute and some of them hold it to that — so set
 * `NUXT_PUBLIC_SITE_URL` in production.
 */
const siteUrl = (process.env.NUXT_PUBLIC_SITE_URL || '').replace(/\/+$/, '')
const absolute = (path: string) => `${siteUrl}${path}`

export default defineNuxtConfig({
  // Same design system as the member app in `apps/pwa`: tokens, type ramp,
  // control recipes, the Tailwind build and the five webfonts.
  extends: ['../../packages/theme'],

  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  // Render cohort content at request time so deployments never bake in a stale cohort.
  nitro: { prerender: { crawlLinks: false } },

  /**
   * The confirmation page is client-only.
   *
   * It exists only for the moment after a payment, and polls for its answer
   * on the client, so there is nothing to render at build time; `ssr: false`
   * also keeps it out of the crawl that `crawlLinks` runs, which would
   * otherwise try to render a payment confirmation with no payment behind it.
   */
  routeRules: {
    '/': { prerender: false, headers: { 'Cache-Control': 'no-store' } },
    '/registration/complete': {
      ssr: false,
      prerender: false,
      // Nothing to index, and a payment confirmation in a search result is a
      // confusing thing to land on. `robots: false` would need the robots
      // module; the header is understood without it.
      headers: { 'X-Robots-Tag': 'noindex, nofollow' },
    },
  },
  modules: ['@vercel/analytics'],
  // A server runtime is required for current Firestore content and checkout.
  // `nuxt generate` cannot provide these API handlers.

  // Auto-import components by filename, matching the PWA's convention, so
  // `components/landing/HeroSection.vue` is `<HeroSection/>`.
  components: [{ path: '~/components', pathPrefix: false, extensions: ['vue'] }],

  css: ['~/assets/styles/main.css'],

  runtimeConfig: {
    /**
     * Server-only, and note the missing `PUBLIC`. Everything under `public`
     * below is compiled into the browser bundle; these are read by the
     * `server/` routes alone and never leave the server.
     *
     * The service account is a project-level credential that bypasses every
     * security rule. It writes `registrations`, which no client may, and it
     * is the identity `createAccessCode` in `apps/functions` accepts when
     * this site asks for a buyer's access code.
     */
    firebaseServiceAccount: process.env.NUXT_FIREBASE_SERVICE_ACCOUNT || '',
    googleApplicationCredentials: process.env.GOOGLE_APPLICATION_CREDENTIALS || '',

    // Where `createAccessCode` answers. Empty builds the deployed URL from
    // the service account's project; set it to reach the emulator, e.g.
    // http://127.0.0.1:5001/recomp-48b7b/africa-south1/createAccessCode
    accessCodeFunctionUrl: process.env.NUXT_ACCESS_CODE_FUNCTION_URL || '',

    // Which database in the project. Empty is `(default)`. Set per environment
    // and never from NODE_ENV, which is `production` for any built bundle
    // including a staging one — the member app's `.env.example` has the long
    // version of this warning.
    firebaseDatabaseId: process.env.NUXT_FIREBASE_DATABASE_ID || '',

    // Temporary fallback only, while the admin console gains these fields.
    // Empty means unavailable; there are no hardcoded cohort/offer defaults.
    registrationCohortId: process.env.NUXT_REGISTRATION_COHORT_ID || '',
    registrationCodeTtlDays: process.env.NUXT_REGISTRATION_CODE_TTL_DAYS || '',


    /**
     * Selar. A product link and a secret, and neither is optional.
     *
     * There is no API key here because there is no API: Selar has no call that
     * initialises a transaction and none that verifies one. The product is
     * created once in their dashboard, carries its own price, and is sold from
     * the hosted page this URL points at — `server/api/register.post.ts` only
     * pre-fills that page and sends the browser to it.
     *
     * Which leaves the secret doing all the work. Selar signs nothing, so the
     * token below is the only thing separating `api/payment/webhook` from
     * anybody who can guess the URL and post a made-up sale. It is generated by
     * us, set on both ends, and wants to be long and random.
     */
    selarProductUrl: process.env.NUXT_SELAR_PRODUCT_URL || '',
    selarWebhookSecret: process.env.NUXT_SELAR_WEBHOOK_SECRET || '',

    /**
     * Brevo, for the one email this site sends: the access code.
     *
     * Not the sign-in email. That one is Firebase's own mailer and stays there
     * — it lives in the member app, and this deployment has no part in it.
     *
     * Unset is a supported state only in the sense that nothing crashes:
     * `sendAccessCodeEmail` warns and reports that it did not send, the seat is
     * still issued, and `emailed: false` is written so it can be found. The code
     * is never rendered anywhere, so a buyer whose email did not send has to be
     * reached by hand.
     */
    brevoApiKey: process.env.NUXT_BREVO_API_KEY || '',
    brevoSenderEmail: process.env.NUXT_BREVO_SENDER_EMAIL || '',
    brevoSenderName: process.env.NUXT_BREVO_SENDER_NAME || 'DP Fitness',
    brevoReplyTo: process.env.NUXT_BREVO_REPLY_TO || '',
    // A template authored in Brevo, so the copy can change without a deploy.
    // Empty uses the designed markup in `server/emails/access-code.ts`.
    brevoTemplateId: process.env.NUXT_BREVO_TEMPLATE_ID || '',

    public: {
      // Where the "Sign in" and "Register" calls-to-action send someone. The
      // member app is a separate deployment, so this is an absolute origin in
      // production and the local PWA dev server otherwise.
      appUrl: process.env.NUXT_PUBLIC_APP_URL || 'http://localhost:3000',

      /**
       * The address the footer publishes, and the same one Brevo sends the
       * access code from — one address the business answers on, configured
       * once. It has to be a sender Brevo has verified either way, which is
       * the thing that keeps it real rather than aspirational.
       *
       * `public` because the footer is rendered on the client too, and a
       * private key is `undefined` there — which would hydrate the address
       * away on a page that had just printed it. That also means the value
       * ships in the page payload, so this is only ever an address meant to
       * be read by anyone who looks.
       *
       * Empty renders no contact row at all. See `footerColumns`.
       */
      contactEmail: process.env.NUXT_BREVO_SENDER_EMAIL || '',

      /**
       * The Instagram handle the footer links to — `dpfitness`, `@dpfitness`
       * or the full profile URL, whichever got pasted in. Empty drops the
       * row.
       *
       * Deployment metadata, separate from Firestore cohort content.
       */
      instagramHandle: process.env.NUXT_PUBLIC_INSTAGRAM_HANDLE || '',

      // Used by the server only when Firestore has no corresponding offer field.
      price: process.env.NUXT_PUBLIC_PRICE || '',
      priceCurrency: process.env.NUXT_PUBLIC_PRICE_CURRENCY || '',


    },
  },

  app: {
    head: {
      htmlAttrs: {
        lang: 'en',
        // The marketing site is a single authored composition — the hero and
        // the closing panel are dark *by design*, on a lavender-white page — so it
        // pins the light palette instead of following the visitor's OS. The
        // member app, where someone spends real time, is the one that flips.
        'data-theme': 'light',
      },
      title: 'DP Fitness · Lose the fat. Keep the muscle. Do both at once.',
      viewport: 'width=device-width, initial-scale=1, viewport-fit=cover',
      meta: [
        { charset: 'utf-8' },
        { name: 'theme-color', content: '#241b2e' },
        {
          name: 'description',
          content:
            'A coached body recomposition challenge for people who are done choosing between losing fat and building muscle. Coached programming, weekly check-ins, and proof you can measure.',
        },
        { property: 'og:type', content: 'website' },
        {
          property: 'og:title',
          content: 'DP Fitness · Lose the fat. Keep the muscle. Do both at once.',
        },
        {
          property: 'og:description',
          content:
            'A coached body recomposition challenge. Coached programming, weekly check-ins, and proof you can measure.',
        },
        /**
         * The share card. `summary_large_image` was already being declared
         * without an `og:image` to back it, which is the one combination that
         * renders worse than claiming nothing: the platform reserves the big
         * slot and then has nothing to put in it, so every shared link
         * unfurled to a blank rectangle.
         *
         * `/brand/og.png` comes from the shared layer like the rest of the
         * artwork. The dimensions are stated because a scraper that knows the
         * size up front can lay the card out without fetching the image first.
         */
        { name: 'twitter:card', content: 'summary_large_image' },
        { property: 'og:image', content: absolute('/brand/og.png') },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:alt', content: 'DP Fitness' },
        { name: 'twitter:image', content: absolute('/brand/og.png') },
        { property: 'og:site_name', content: 'DP Fitness' },
        // Only when the origin is actually known: a relative `og:url` is
        // meaningless, where a relative `og:image` at least resolves.
        ...(siteUrl ? [{ property: 'og:url', content: siteUrl + '/' }] : []),
      ],
      // Everything under `/brand/` is served out of the shared design-system
      // layer, not this app's `public/`, so the tab icon here and the one on a
      // member's home screen are the same file rather than two copies that can
      // drift. Regenerate the set with `bun run brand:assets` after changing
      // anything in `/logo`; don't retouch a PNG by hand.
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/brand/favicon.svg' },
        { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/brand/favicon-32.png' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/brand/apple-touch-icon.png' },
      ],
    },
  },
})
